name: First CI Pipeline

on:
  push:
    branches: ["main"] #chạy khi có code đẩy vào nhánh main
  pull_request:
    branches: ["main"] #chạy khi có ai đó tạo PR vào main

jobs:
  say-hello:
    runs-on: ubuntu-latest #Chạy trên ubuntu mới nhất

  steps:
    #Lấy code của mình về máy ảo này
    - name: Checkout code
      uses: actions/checkout@v4

  #chạy lệnh linux cơ bản
    - name: Say hello
      run: |
        echo "Xin chào! Đây là máy ảo của github"
        echo "Tôi đang chạy trên hệ điều hành:"
        uname -a
  #Kiểm tra xem có file readme không
    - name: Checkfiles
      run: ls -la
